spring:
  # 1. Spring Profile 설정 (로컬에서는 dev, 배포 시에는 prod 사용)

  profiles:
    active: dev # 로컬에서 실행 시 기본적으로 dev 프로필 활성화

  # 2. Spring Boot 전체 설정

  application:
    name: leafy

  # ✨ data.sql 실행을 위한 설정
  sql:
    init:
      mode: always      # 항상 실행 (ON CONFLICT 덕분에 안전함)
      encoding: UTF-8   # 한글 깨짐 방지

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  # (1) Jackson (JSON) 설정
  jackson:
    serialization:
      fail-on-empty-beans: false
    property-naming-strategy: SNAKE_CASE

  # (2) 데이터베이스(PostgreSQL) & JPA 공통 설정
  datasource:
    driver-class-name: org.postgresql.Driver # 드라이버 클래스 이름은 공통
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        default-batch-fetch-size: 100
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  # --- OAuth2 Client 공통 설정 ---
  security:
    oauth2:
      client:
        provider: # Provider 정보는 공통
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  cloud:
    aws:
      region:
        static: ap-northeast-2
      stack:
        auto: false

# 3. 서버 기본 설정
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

# 4. Swagger (SpringDoc) 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
  default-consumes-media-type: application/json;charset=UTF-8

# --- 🔐 JWT 설정 ---
jwt:
  expiration: 86400000 # 토큰 만료 시간은 공통으로 사용


# --- 외부 API 공통 설정 ---
plant:
  id:
    base-url: https://plant.id/api/v3 # API 기본 URL은 공통
kma:
  api:
    url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst # 기상청 API URL
nongsaro: # Nongsaro API 설정 추가
  api:
    base-url: http://api.nongsaro.go.kr/service/garden/gardenList
    detail-url: http://api.nongsaro.go.kr/service/garden/gardenDtl
    image-base-url: http://www.nongsaro.go.kr/cms_contents/301/
kakao: # Kakao API 설정 추가
  api:
    base-url: https://kapi.kakao.com
  auth:
    base-url: https://kauth.kakao.com

logging:
  level:
    com.leafy: DEBUG